---

- name: "Restart fail2ban"
  become: true
  ansible.builtin.service:
    name: "{{ fail2ban_service_name }}"
    state: "restarted"
  when:
    - "fail2ban_service"
    - "fail2ban_service_state == 'started'"
